In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("customer_queries_dataset.csv")
df.head()

                                query            label
0   Can you update me on my delivery?     Order Status
1        How long does delivery take?    Shipping Info
2               I forgot my password.    Account Issue
3  What are the specs of this laptop?  Product Inquiry
4           I want to return my item.          Returns

In [8]:
df.shape

(210, 2)

In [9]:
df['label'].value_counts()

label
Order Status       35
Shipping Info      35
Account Issue      35
Product Inquiry    35
Returns            35
Technical Issue    35
Name: count, dtype: int64

In [10]:
df['cleaned_query'] = df['query'].str.lower()
df['cleaned_query'] = df['cleaned_query'].str.replace(r'[^A-Za-z0-9 ]+', '',regex=True)
df['cleaned_label'] = df['label'].str.lower()
df

,query,label,cleaned_query,cleaned_label
0,Can you update me on my delivery?,Order Status,can you update me on my delivery,order status
1,How long does delivery take?,Shipping Info,how long does delivery take,shipping info
2,I forgot my password.,Account Issue,i forgot my password,account issue
3,What are the specs of this laptop?,Product Inquiry,what are the specs of this laptop,product inquiry
4,I want to return my item.,Returns,i want to return my item,returns
...,...,...,...,...
205,Why is the website so slow?,Technical Issue,why is the website so slow,technical issue
206,What is the status of my shipment?,Order Status,what is the status of my shipment,order status
207,Why is my account locked?,Account Issue,why is my account locked,account issue
208,Is this item still in stock?,Product Inquiry,is this item still in stock,product inquiry
209,How do I reset my login details?,Account Issue,how do i reset my login details,account issue

,query,label,cleaned_query,cleaned_label
0,Can you update me on my delivery?,Order Status,can you update me on my delivery,order status
1,How long does delivery take?,Shipping Info,how long does delivery take,shipping info
2,I forgot my password.,Account Issue,i forgot my password,account issue
3,What are the specs of this laptop?,Product Inquiry,what are the specs of this laptop,product inquiry
4,I want to return my item.,Returns,i want to return my item,returns
...,...,...,...,...
205,Why is the website so slow?,Technical Issue,why is the website so slow,technical issue
206,What is the status of my shipment?,Order Status,what is the status of my shipment,order status
207,Why is my account locked?,Account Issue,why is my account locked,account issue
208,Is this item still in stock?,Product Inquiry,is this item still in stock,product inquiry
209,How do I reset my login details?,Account Issue,how do i reset my login details,account issue

In [12]:
df.to_csv("Customer_query_classificatio.csv",index= False)